version: "3.7"

services:
  mysql:
    image: mysql:8.0.27
    container_name: billingApp_mysql
    environment:
      MYSQL_DATABASE: billingApp
      MYSQL_ROOT_PASSWORD: 123qweASD.
      MYSQL_USER: application_user
      MYSQL_PASSWORD: 123123aa
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    ports:
      - 3382:3306
    volumes:
      - billingApp_mysql:/data/mysql
    networks:
      - billingApp_project

volumes:
  billingApp_mysql:
    driver: local

networks:
  billingApp_project:
    driver: bridge
